config/routes.rb
Rails.application.routes.draw do
  resources :kids

end

app/models/kid.rb
class Kid < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name, :age, :hight, :weight, :hobby)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :hight %><br>
    <%= f.number_field :hight %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :hobby %><br>
    <%= f.text_field :hobby %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<br>
<br>
<h1>Editing Kid</h1>

<%= render 'form' %>

<%= link_to 'Show', @kid %> |
<%= link_to 'Back', kids_path %>
    

app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>
<br><br><br>
<h1>Listing Kids</h1>
<% @kids.each do |kid| %>
<table class="table">
  
    <thead>
      <tr>
        <th>Name</th>
        <th>Age</th>
        <th>Hight</th>
        <th>Weight</th>
        <th>Hobby</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.age %></td>
        <td><%= kid.hight %></td>
        <td><%= kid.weight %></td>
        <td><%= kid.hobby %></td>
      </tr>
    </tbody>
  </table>
      <tr>
        <button class="btn btn-default" type="submit"><%= link_to 'Show', kid %></button>
        <button class="btn btn-default" type="submit"><%= link_to 'Edit', edit_kid_path(kid) %></button>
        <button class="btn btn-default" type="submit"><%= link_to 'Delete', kid, method: :delete, data: { confirm: 'Are you sure?' } %></button>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br><br>
<button class="btn btn-default" type="submit"><%= link_to 'New Kid', new_kid_path %></button>

app/views/kids/new.html.erb
<br>
<br>
<div align="center">
    <h1>New Kid</h1>

<%= render 'form' %>

<%= link_to 'Back', kids_path %>
</div>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>
<br><br>
<p>
  <strong>Name:</strong>
  <%= @kid.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @kid.age %>
</p>

<p>
  <strong>Hight:</strong>
  <%= @kid.hight %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @kid.weight %>
</p>

<p>
  <strong>Hobby:</strong>
  <%= @kid.hobby %>
</p>

<%= link_to 'Edit', edit_kid_path(@kid) %> |
<%= link_to 'Back', kids_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyKid</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">HappyKid</a>
        </div>
      </div>
    </nav>
<%= yield %>

</body>
</html>